"""
TransitFlow — Neo4j Data Verification Utility
=============================================
This module runs automated integration checks to guarantee structural parity
between the raw source JSON payloads and the populated Neo4j property graph.
"""

import json
import os
import sys

# Append the current directory to path to ensure proper module resolution
sys.path.insert(0, ".")

from neo4j import GraphDatabase
from skeleton.config import NEO4J_URI, NEO4J_USER, NEO4J_PASSWORD

# Locate the target data directory dynamically relative to this script path
_DATA_DIR = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "train-mock-data")
)

def load_json(filename):
    """Helper function to load mock JSON and index by station_id for O(1) lookups."""
    with open(os.path.join(_DATA_DIR, filename), encoding="utf-8") as f:
        return {station["station_id"]: station for station in json.load(f)}

def verify_data():
    # 1. Load Raw Source JSON Files
    print("📋 Loading raw source JSON payloads...")
    json_metro = load_json("metro_stations.json")
    json_rail = load_json("national_rail_stations.json")
    
    # 2. Initialize connection to Neo4j Instance
    print("🌐 Connecting to Neo4j database instances...")
    driver = GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))
    
    error_count = 0
    
    with driver.session() as session:
        # ---- CHECK A: Validate MetroStation Nodes ----
        print("\n🔍 Validating MetroStation graph nodes against source schemas...")
        result = session.run("MATCH (m:MetroStation) RETURN m")
        db_metro_count = 0
        
        for record in result:
            db_metro_count += 1
            node = record["m"]
            st_id = node["station_id"]
            
            # Why: Defensive check to catch rogue node IDs generated by improper seed scripts
            if st_id not in json_metro:
                print(f"❌ Structural Defect: Station ID '{st_id}' found in Neo4j but missing from JSON source.")
                error_count += 1
                continue
                
            js_data = json_metro[st_id]
            if node["name"] != js_data["name"]:
                print(f"❌ Attribute Mismatch for '{st_id}': Graph Name '{node['name']}' != JSON Name '{js_data['name']}'")
                error_count += 1

        if db_metro_count != len(json_metro):
            print(f"❌ Node Volume Variance: Expected {len(json_metro)} MetroStations, found {db_metro_count} in database.")
            error_count += 1
        else:
            print(f"✅ MetroStation core profiles verified successfully ({db_metro_count} records aligned).")

        # ---- CHECK B: Validate NationalRailStation Nodes ----
        print("\n🔍 Validating NationalRailStation graph nodes against source schemas...")
        result = session.run("MATCH (r:NationalRailStation) RETURN r")
        db_rail_count = 0
        
        for record in result:
            db_rail_count += 1
            node = record["r"]
            st_id = node["station_id"]
            
            if st_id not in json_rail:
                print(f"❌ Structural Defect: Station ID '{st_id}' found in Neo4j but missing from JSON source.")
                error_count += 1
                continue
                
            js_data = json_rail[st_id]
            if node["name"] != js_data["name"]:
                print(f"❌ Attribute Mismatch for '{st_id}': Graph Name '{node['name']}' != JSON Name '{js_data['name']}'")
                error_count += 1

        if db_rail_count != len(json_rail):
            print(f"❌ Node Volume Variance: Expected {len(json_rail)} NationalRailStations, found {db_rail_count} in database.")
            error_count += 1
        else:
            print(f"✅ NationalRailStation core profiles verified successfully ({db_rail_count} records aligned).")

        # ---- CHECK C: Validate Adjacent Line Edge Connectivity ----
        print("\n🔍 Validating transit link topology (METRO_LINK / RAIL_LINK)...")
        metro_links = session.run("MATCH ()-[r:METRO_LINK]->() RETURN count(r) AS c").single()["c"]
        rail_links = session.run("MATCH ()-[r:RAIL_LINK]->() RETURN count(r) AS c").single()["c"]
        
        # Design Choice: Calculate total expected edges mathematically from adjacency vectors
        expected_metro_links = sum(len(s["adjacent_stations"]) for s in json_metro.values())
        expected_rail_links = sum(len(s["adjacent_stations"]) for s in json_rail.values())
        
        if metro_links != expected_metro_links:
            print(f"❌ Link Volume Mismatch: METRO_LINK graph count {metro_links} != Expected {expected_metro_links}")
            error_count += 1
        else:
            print(f"✅ Metro adjacent route topology counts matched perfectly ({metro_links} links).")
            
        if rail_links != expected_rail_links:
            print(f"❌ Link Volume Mismatch: RAIL_LINK graph count {rail_links} != Expected {expected_rail_links}")
            error_count += 1
        else:
            print(f"✅ National Rail adjacent route topology counts matched perfectly ({rail_links} links).")

        # ---- CHECK D: Validate Inter-Network Transfer Topologies (INTERCHANGE_TO) ----
        # Why: Ensures dual-network bridge edges are fully functional to allow multi-modal query traversal.
        print("\n🔍 Verifying multi-modal cross-network interchange links...")
        interchanges = session.run("MATCH ()-[r:INTERCHANGE_TO]->() RETURN count(r) AS c").single()["c"]
        
        # Count explicit transfer mappings defined inside the source records
        expected_interchanges = sum(1 for s in json_metro.values() if s["is_interchange_national_rail"] and s["interchange_national_rail_station_id"])
        # Bidirectional multiplication factor (Metro -> Rail AND Rail -> Metro)
        expected_total_interchanges = expected_interchanges * 2
        
        if interchanges != expected_total_interchanges:
            print(f"❌ Interchange Topology Failure: Database has {interchanges} links, expected {expected_total_interchanges}")
            error_count += 1
        else:
            print(f"✅ Bidirectional interchange graph links verified successfully ({interchanges} paths mapped).")

    driver.close()
    
    # 3. Final Integration Report Evaluation Summary
    print("\n==================================================")
    print("           GRAPH VERIFICATION SUMMARY             ")
    print("==================================================")
    if error_count == 0:
        print("🏆 SUCCESS: Neo4j Graph Database matches mock JSON specifications with 100% precision!")
    else:
        print(f"🚨 INTEGRITY CRASH: Graph verification failed with {error_count} structural errors.")
        print("   Please review your schema constraint seeding scripts.")
    print("==================================================")

if __name__ == "__main__":
    verify_data()